name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get the version number
        run: echo "VERNUM=$(awk -F'\"' '/version_number/ { print $4 }' manifest.json)" >> $GITHUB_ENV

      - name: Compress all files into an archive named {repository}-{version}.zip
        run: zip -r ${{ github.repository }}-${{ env.VERNUM }}.zip .

      - name: Upload artifact as release asset
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.repository }}-${{ env.VERNUM }}.zip
          path: ${{ github.repository }}-${{ env.VERNUM }}.zip
